Import('qt_env')

env = qt_env.Clone()

env.AppendUnique(CPPDEFINES = [ 'INSTALLERQUICK_LIBRARY' ])

# Le sigh
env['CPPPATH'] += [ '.' ]

env.Uic4(env.Glob('*.ui'))

lib = env.SharedLibrary('installerQuick', env.Glob('*.cpp'))
env.InstallModule(lib)
